### ISSUE TITLE
Magisk alpha has missed compatibility with Official Magisk

### ISSUE THREAD

**Issue by privacyguy123** [Magisk-Modules-Alt-Repo/usb-samplerate-unlocker#13] opened 2024-03-05 14:49 UTC
Even latest Canary "pure Magisk" has ditched mirrors and I would hope these modules can update their installation scripts to cater for it. :)

**Comment by yzyhk904** [comment] 2024-03-06 04:54
I've tested the latest canary Magisk now and found it had mirror file systems as the stable.

Don't you talk about another Magisk variant? Magisk alpha or something?

**Comment by privacyguy123** [comment] 2024-03-06 21:59
I'm certain Johwu pushed this mirrorless setup to Canary 26.4 onward?

I'm on Alpha yes - I had a previous version of your module installed fine but this newest update is complaining about variant - perhaps customize.sh can be edited to suit mirrorless Magisk? I know the guys over in the audio mod community have fixed JamesDSP and Viper to work fine with it. :)

**Comment by yzyhk904** [comment] 2024-03-07 11:47
I think it's wrong. He said that he tried to change Magisk's mounting system, but abandoned (at this time?) because of compatibility issues. This doesn't mean excluding mirrors for module installation (esp. "customize.sh"). Even overlay mount system could provide mirrors.

My previous version hasn't been fine for magisk alpha, kernelSU, Kitsune magisk from mid February about installation and updating (excluding daily execution) because of lacking mirrors. I added checking mirrors only because of avoiding serious problems by no mirrors, e.g., no audio even for internal speakers on Tensor devices.

I consider mirrors are needed for safe and intended installation by using "customize.sh" because of avoiding modification of itself and other modules. And I think those above modules hasn't been using mirrors for installation from the beginning. So their installation may be interfered by others.

**Comment by privacyguy123** [comment] 2024-03-07 22:53
Version 1.5.4 installed fine, it's only this newest 1.5.5 that complains about "variant."

I think variant should be irrelevant as all Magisk work very similarly under the hood and there's no reason why this module can't work on all of them. :)

JamesDSP and Viper definitely relied on mirrors in their install scripts - I worked with the devs directly in Telegram to get it working again.

**Comment by yzyhk904** [comment] 2024-03-08 02:26
It's not true. Version 1.5.4 doesn't work well unless mirrors. It doesn't show "abort" message, but installs wrongly and silently. See issues of other persons here.

Please provide mirrors. I think Magisk alpha and Kitsune Magisk has a build option for providing mirrors.
I don't think the variants without mirrors are relevant.

Edit: Similarity means nothing. Compatibility is truly important!

**Comment by yzyhk904** [comment] 2024-03-09 15:22
As you said so, I see the source of a JamesDSP magisk module. The module mounts mirrors by itself internally. This means the module is compatible for both  pure magisk, kernelSU, and other magisk variants, and tested on all of them.

My module is tested on pure magisk only, so may run on compatible magisk variants (having mirrors) intendedly but cannot on other incompatible magisk variants (not having mirrors).

**Comment by privacyguy123** [comment] 2024-03-09 20:23
You seem reluctant to update the code for other Magisk variants - I'll try to edit the code myself based on JamesDSP and Viper workaround. I don't think your module should **need** mirrors to function properly ...


> My module is tested on pure magisk only, so may run on compatible magisk variants (having mirrors) intendedly but cannot on other incompatible magisk variants (not having mirrors).

If it works on "pure" Magisk it's a pretty safe bet it's fine on the other variants!

**Comment by yzyhk904** [comment] 2024-03-10 02:54
It's not true. I'm willing to magisk variants (especially compatible ones)!

For example, [USB_SampleRate_Changer](https://github.com/yzyhk904/USB_SampleRate_Changer) and [Audio Jitter Silencer](https://github.com/Magisk-Modules-Alt-Repo/audio-jitter-silencer) may work on mirror-less magisk variants.

JamesDSP (also Viper?) module mounts mirrors by itself. You are confused. I think only this module of mine could change compatible to Magisk alpha relatively easily without mirrors though. But you need keep testing on Magisk alpha.

**Comment by privacyguy123** [comment] 2024-03-12 10:22
I can test your builds on Magisk Alpha. :)

As far I can see you are using mirrors to run hexpatch scripts on every bootup - I think it's safe to just hexpatch the values directly on initial install then revert them back to default on uninstall no?

**Comment by yzyhk904** [comment] 2024-03-12 13:34
No, No, No. It's for changing the max sampling rate only by editing "post-fs-data.sh" already installed when users need. The script doesn't need mirrors really, but its code was moved from "customize.sh" un-modified then.

Do you mean you would build Magisk alpha with the mirroring build option? It's simplest and easiest!

**Comment by yzyhk904** [comment] 2024-03-13 11:03
A very simple idea came to me, and I made a "post-fs-data.d" script to mount mirror file systems on Magisk alpha and others. The script was tested slightly on Magisk alpha.

Unzip [post-fs-data-mounting-mirrors.zip](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/files/14586505/post-fs-data-mounting-mirrors.zip), and move the script into "/data/adb/post-fs-data.d", then execute a command "chmod +x post-fs-data-mounting-mirrors.sh".

After rebooting, you could install my (pure) magisk compatible modules!

**Comment by privacyguy123** [comment] 2024-03-14 12:41
> A very simple idea came to me, and I made a "post-fs-data.d" script to mount mirror file systems on Magisk alpha and others. The script was tested slightly on Magisk alpha.
> 
> Unzip [post-fs-data-mounting-mirrors.zip](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/files/14586505/post-fs-data-mounting-mirrors.zip), and move the script into "/data/adb/post-fs-data.d", then execute a command "chmod +x post-fs-data-mounting-mirrors.sh".
> 
> After rebooting, you could install my (pure) magisk compatible modules!

Interesting - could this script possibly cause any problems somewhere else? 

Do I need to run it on every reboot?

**Comment by privacyguy123** [comment] 2024-03-14 16:52
I tried this today and it caused extreme device wide lag although I was able to install your module then delete the script. Am I misunderstanding maybe this was what you intended for me to do in the first place?

i still don't understand why the install script for the module can't be altered to suit other Magisk variants - after all you are just copying patched lib files into system ?

**Comment by yzyhk904** [comment] 2024-03-15 02:52
There isn't any reason why that should happen. Probably depend on devices or Magisk alpha isn't optimized to that.

I consider you should request Magisk alpha dev. to be compatible with Official Magisk. This issue has been caused by Magisk alpha and other incompatible variants.

**Comment by privacyguy123** [comment] 2024-03-15 09:08
Magisk will push mirrorless setup soon - then what? Dev has announced it already

**Comment by yzyhk904** [comment] 2024-03-15 14:01
It's Magisk alpha only, so what?

I released [Compatible Magisk-mirroring](https://github.com/yzyhk904/compatible-magisk-mirroring) for installing my other modules on incompatible Magisk variants and KernekSU.

**Comment by privacyguy123** [comment] 2024-03-16 13:13
Topjohnwu has already announced that "pure" Magisk will ship with no mirrors in new versions, he is just very slow to push changes. What will you do then? 

> I released [Compatible Magisk-mirroring](https://github.com/yzyhk904/compatible-magisk-mirroring) for installing my other modules on incompatible Magisk variants and KernekSU.

Isn't this just the script that slowed my phone down inside a Magisk module?

**Comment by yzyhk904** [comment] 2024-03-16 14:42
Show me the exact sentences and its source. I doubt this! New Magisk adopting overlayfs doesn't mean not providing mirrors. 

I wouldn't do anything about this till a newly released official Magisk changes really.

My module doesn't slow down my devices. Only yours.

**Comment by privacyguy123** [comment] 2024-03-16 16:54
> Show me the exact sentences and its source. I doubt this! New Magisk adopting overlayfs doesn't mean not providing mirrors.
> 
> I wouldn't do anything about this till a newly released official Magisk changes really.
> 
> My module doesn't slow down my devices. Only yours.

The code was reverted in latest "pure" Magisk  Canary (v27.0) due to complaints about compatibility. The mirrorless code will be pushed some time in the future and is a planned changed - I don't have source, I was told by Alpha/ZygiskNext/Lsposed developers. 

Good, it's coming and module developers will need to be less lazy/reluctant to change and adapt. 

It's your "compatibility" script that slows down the device, Alpha is not meant to have mirrors mounted I imagine.

**Comment by yzyhk904** [comment] 2024-03-17 04:54
My doubt is correct. You show me the truth! He would push his mirrorless code, but keep compatibility.

My mirroring module wouldn't slow down devices except yours. It's a special effect only on yours because Official Magisk and JamesDSP having the same mirroring doesn't slow down devices significantly!

I close this issue. It's meaningless!

**Closed as completed by yzyhk904** 2024-03-17 04:54 UTC
Labels: request

**Comment by privacyguy123** [comment] 2024-03-17 11:33
> My mirroring module wouldn't slow down devices except yours. It's a special effect only on yours because Official Magisk and JamesDSP having the same mirroring doesn't slow down devices significantly!

Yes, this is the problem - I'm on Magisk Alpha and I don't think it should have mirrors mounted, this is what's causing the slow down perhaps. 

No mirrors are coming in "pure" Magisk - we can revisit this when it happens.

**Comment by yzyhk904** [comment] 2024-03-17 15:33
Ridiculous! Official Magisk doesn't slow down devices. What do you explain about this?

Official Magisk might adopt a mirrorless mount system, but would keep compatibility! That means it would provide mirrors (unmodified original system files). "Mirrorless" mount system doesn't mean not providing "mirrors"!
